### ISSUE TITLE
does not work fosslight_scanner in Windows 10 

### ISSUE THREAD

**Issue by kjhcav** [fosslight/fosslight_scanner#44] opened 2022-08-25 05:21 UTC
**Describe the bug**
does not work fosslight_scanner in Windows 10 Home 21H2

**To Reproduce**
fosslight_scanner
What are you going to analyze? (1/2)
                   1. Links that can be cloned by git or wget
                   2. Local source path
1
Enter the link to analyze:https://github.com/LGE-OSS/example

**Expected behavior**

Enter the link to analyze:https://github.com/LGE-OSS/example
Link to download: https://github.com/LGE-OSS/example
* FOSSLight Downloader - Result :False
module 'signal' has no attribute 'SIGALRM'
Download failed: module 'signal' has no attribute 'SIGALRM'

**System environment (please complete the following information):**
 - OS: Windows 10 Home 21H2
 - Python : python 3.9.12 (with Anaconda 3)

**Comment by kjhcav** [comment] 2022-08-25 05:23
![fosslight_scanner_error](https://user-images.githubusercontent.com/70565889/186581504-b1961b37-e5dd-42c8-bc32-8bbe14031c65.png)

**Comment by soimkim** [comment] 2022-08-25 05:43
@kjhcav , Thanks for reporting the error. 😃

**Comment by soimkim** [comment] 2022-09-02 07:40
@kjhcav ,
This bug was caused by using a module that is not available in Windows. 
This is a bug that occurred in [FOSSLight Util](https://github.com/fosslight/fosslight_util/releases/tag/v1.4.10), a sub-package, and should be fixed by installing v1.4.10 of FOSSLight Util.

Therefore, it is recommended to use `pip install fosslight_scanner --force-reinstall --upgrade` to upgrade the version.

**Closed by soimkim** 2022-09-02 07:40 UTC
Labels: bug
